---
- name: Configure network devices
  hosts: cisco_iol
  gather_facts: false
  strategy: free

  tasks:
    - name: Load shared network group variables
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../group_vars/cisco_iol/main.yml"

    - name: Load feature-specific host variables
      ansible.builtin.include_vars:
        file: "{{ feature_host_vars_dir }}/{{ inventory_hostname }}.yaml"

    - name: Configure {{ inventory_hostname }}
      cisco.ios.ios_config:
        src: "{{ feature_templates_dir }}/{{ config_template }}"